services:

  mysql:
    image: mysql:latest  
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - p-mysql-volume:/var/lib/mysql

  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - p-postgres-volume:/var/lib/postgresql
 
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3307:3306
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

    volumes:
      - p-mariadb-volume:/var/lib/mariadb
  
  ## SGBD 

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8082:80 
    links:
      - mysql
      - mariadb
    environment:
      PMA_HOSTS: mysql, mariadb
      PMA_PORTS: 3306, 3306
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8083:8080
    restart: always


volumes:
  p-mysql-volume:
  p-postgres-volume:
  p-mariadb-volume: